fixed Dockerfile

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -24,7 +24,19 @@ jobs:
 
             - name: Setup Docker Buildx
               uses: docker/setup-buildx-action@v3
+            - name: Check Secrets
+              run: |
+                  if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
+                  echo "DOCKER_USERNAME is missing"
+                  exit 1
+                  fi
 
+                  if [ -z "${{ secrets.DOCKER_TOKEN }}" ]; then
+                  echo "DOCKER_TOKEN is missing"
+                  exit 1
+                  fi
+
+                  echo "Secrets found."
             - name: Login to Docker Hub
               uses: docker/login-action@v3
               with:
